### ISSUE TITLE
defaultContext not working on subsequent transactions (or queries)

### ISSUE THREAD

**Issue by jakep36** [fluree/http-api-gateway#17]
# Update / what this card now covers

OK this one got a little crazy. Here's the work this card now covers from #19:

- Actually gives an error message and status code when something goes wrong instead of always "500 error - it was an ExceptionInfo! I'm helping!"
    - in https://github.com/fluree/http-api-gateway/pull/19/commits/40ba824f27384be5264c0afd4ba02d5a17889486
- Renames API root path from `/fdb/` to `/fluree/` as this seems to be the new hotness in JSON-LD land (i.e. it matches the typical Clojure alias for the `j.d.json-ld.api` ns). If it ain't broke, break it! 
    - in https://github.com/fluree/http-api-gateway/pull/19/commits/e246f42e9259839d19f7058c479918bdb6e8e1aa
- Gets rid of `:action :new` & `:defaultContext` on the `/transact` endpoint and adds a new `/create` endpoint that takes a top-level (optional) `:context` param. The `/create` endpoint still requires an initial `:txn` to be included so that the resulting ledger is loadable from storage afterwards. 
    - in https://github.com/fluree/http-api-gateway/pull/19/commits/e79337ea7e88732f3cbb4dd6209ab3d6f3e89e5f & https://github.com/fluree/http-api-gateway/pull/19/commits/40ba824f27384be5264c0afd4ba02d5a17889486
    - This is based on DX feedback from the Nexus team and others on the core team that the old approach was kind of confusing at times.
- It uses https://github.com/fluree/db/pull/375 and so switches from `:js? true` to `:context-type :string` 
    - in https://github.com/fluree/http-api-gateway/pull/19/commits/5e566c3a62cb0f598f7d1fee6c2f5591d929316d
    - ...unless it's an EDN request in which case it uses `:context-type :keyword` so those can still work.
- It fixes an annoyance I had w/ the original config merging code where it was duplicating effort and clobbering some config you might actually want b/c I didn't fully understand how donut's config overriding worked. Now I do. A little (more).
    - in https://github.com/fluree/http-api-gateway/pull/19/commits/3b1e504a39fc07ca0fc3c39c66ce3646a6306706
- It adds a `run-dev` alias so you can start this thing in dev mode by running `clojure -X:run-dev`
    - uncredited in https://github.com/fluree/http-api-gateway/pull/19/commits/890d8cdccf0ff068c77df512c6e3138a1556df35
- It adds tests! Just two tests for the `/create` endpoint for now. Adding more will require making the `load` API fn work for memory conns (🎉) or using a file conn in the tests (☹️).
    - in https://github.com/fluree/http-api-gateway/pull/19/commits/890d8cdccf0ff068c77df512c6e3138a1556df35
    - run them with `clojure -X:test`

# Original issue

transacting this to the http-api to create a ledger:

```
{
    "action": "new",
    "ledger": "fluree-jld/q0001",
    "txn": {
        "id": "blueberry:one",
        "name": "one"
    },
    "defaultContext": {
        "id": "@id",
        "type": "@type",
        "schema": "http://schema.org/",
        "ex": "http://example.org/ns/",
        "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
        "rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
        "xsd": "http://www.w3.org/2001/XMLSchema#",
        "blueberry": "https://www.blueberry.com/"
  }
}
```

The subject appears correct when I query for it. But when I use `blueberry:` on a subsequent transaction it doesn't seem to use the dafultContext anymore.

Seeing this in the logs:

`"Invalid db default context, unable to parse: 150"`

`id` doesn't work on the 2nd transaction either and I need `@id` so I think `defaultContext` is working on the `action: new` transaction but not subsequent transactions

**Comment by cap10morgan** [comment]
The current defaultContext behavior is a little tricky to reason about (where it becomes the persisted defaultContext for the ledger only if it doesn't already have one; which should have happened here since presumably it's a new ledger). @jakep36 suggested it might be more intuitive to have a new endpoint (e.g. `/create` to mirror the clj API) that accepts a ledger name and initial transaction. Then that endpoint would be the only one to accept a `defaultContext` and the existing `/transact` endpoint would only accept a `context`.

That seems more intuitive to me too, but curious what others think.

**Comment by cap10morgan** [comment]
@jakep36 discovered that this seems to be unrelated to either the http-api-gateway or string contexts. He got the error in a db REPL using a keyword context. But of course not every interaction w/ main HEAD of db is producing that error, so we're trying to figure out what is causing it.

**Comment by cap10morgan** [comment]
This bug card needs to be completely rewritten based on our investigations. This wasn't at all what we thought it was. I'll do the rewrite as soon as I can.
