### ISSUE TITLE
Multi-query default context

### ISSUE THREAD

**Issue by haliechm** [fluree/http-api-gateway#23]
**Must provide context when hitting the multi-query endpoint (default context does not seem to be used):**

1. Single query for rdfs:Class [works] (note: no context was provided):

![dc-00](https://user-images.githubusercontent.com/40928883/220153883-cc767b32-76a9-4f6a-b5fa-3b2b6e358b46.png)
![dc-01](https://user-images.githubusercontent.com/40928883/220153945-e1c1877f-a712-44b9-87ec-b0cf935e917a.png)

2. Multi-query for rdfs:Class w/o providing context [does not work - rdfs not found] (note: no context provided):

![dc-02](https://user-images.githubusercontent.com/40928883/220154049-0aa73abb-c86b-46d1-b49b-f8e24b82d822.png)
![dc-04](https://user-images.githubusercontent.com/40928883/220154230-b66b5d47-c3d1-4b80-ba90-5da27442ac57.png)
![dc-05](https://user-images.githubusercontent.com/40928883/220154249-93f44663-a6e3-41aa-8130-99f4a4c41806.png)

3. Multi-query for rdfs:Class providing context [works] (note: must provide context for rdfs):
![dc-06](https://user-images.githubusercontent.com/40928883/220154441-8a445d46-9875-4c2b-bf5a-4ce4988d9576.png)
![dc-07](https://user-images.githubusercontent.com/40928883/220154466-0ee4f140-f6d8-4d12-bff3-5e48964f4ce6.png)

**Default context provided when creating ledger:**
```
{
    "id": "@id",
    "type": "@type",
    "xsd": "http://www.w3.org/2001/XMLSchema#",
    "rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
    "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
    "sh": "http://www.w3.org/ns/shacl#",
    "schema": "http://schema.org/",
    "skos": "http://www.w3.org/2008/05/skos#",
    "wiki": "https://www.wikidata.org/wiki/",
    "f": "https://ns.flur.ee/ledger#"
}
```

**HTTP-Api Gateway commit:** ef1d0ce
**DB commit:** f68e7fd

**Comment by cap10morgan** [comment]
I have a hunch that https://github.com/fluree/http-api-gateway/pull/22 may fix this.

**Comment by haliechm** [comment]
Also note on the last screenshot, the 'id' comes back as "schema/Restaurant" where I would have expected it to come back as "schema:Restaurant"

**Comment by cap10morgan** [comment]
I have _another_ hunch that #29 might fix this. :)

**Comment by zonotope** [comment]
I have a theory that the issue is the way multi-query handles query options. My suspicion is that the `:context-type` key isn't being set correctly in multi query sub queries because that key is passed in as a top-level option. i have not had a chance to test this theory yet, but i have a strong suspicion that that's what it is.
