### ISSUE TITLE
All responses (e.g. 400) should have Access-Control-Allow-Origin header

### ISSUE THREAD

**Issue by aaj3f** [fluree/http-api-gateway#24]
I'm seeing that there's a `wrap-cors` middleware being applied on requests against the `/fluree` path, however, when I issue requests using JS HTTP clients, I'm not seeing responses w/ the access-control-allow-origin header and am having to manually inject it to allow my browser to handle the response.

![Image](https://user-images.githubusercontent.com/21989859/220462043-92e5518f-21ea-424c-9342-80929c1981f0.png)

If you want to, you can see the HTTP requests coming off of this react app: https://github.com/fluree/time-travel-app-v3. For me, the app interacts successfully against http-api-gateway when I use a browser extension to manually add `access-control-allow-origin: *` to HTTP responses, but when I turn it off, no such headers arrive on responses from http-api-gateway

**Comment by cap10morgan** [comment]
This works with the latest code when there isn't some other problem leading to a non-200 response.

**Comment by aaj3f** [comment]
The main issue is w/ 400s. If only 200s get the `access-control-allow-origin` header, then client apps (in, say, a browser that's blocking responses without `access-control-allow-origin`) can't introspect on the error message accompanying that 400.

So in the following example the first request targets a legit ledger and structures a query for an `rdf:type` that exists on that ledger (`schema:Person`). We get a 200, it has the ACAO header.

In the 2nd request, we target the same ledger but query for an `rdf:type` that doesn't exist (`ex:LakeMonster`). We get a 400 (as we should) but it doesn't have the ACAO header. A browser like Chrome wouldn't surface the response error data at all without that ACAO header

```bash
MacBook-Pro-6:~ ajohnson$ curl -v --location --request POST 'http://localhost:58090/fluree/query' \
--header 'Origin: http://localhost:3000' \
--header 'Content-Type: application/json' \
--data-raw '{
    "ledger": "examples/headers",
    "query": {
        "select": "?s",
        "where": [
            ["?s", "rdf:type", "schema:Person"]
        ]
    }
}'
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 127.0.0.1:58090...
* Connected to localhost (127.0.0.1) port 58090 (#0)
> POST /fluree/query HTTP/1.1
> Host: localhost:58090
> User-Agent: curl/7.84.0
> Accept: */*
> Origin: http://localhost:3000
> Content-Type: application/json
> Content-Length: 159
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< X-Fdb-Fuel: 1000
< Access-Control-Allow-Methods: GET, POST
< Access-Control-Allow-Origin: http://localhost:3000
< Content-Type: application/json;charset=utf-8
< Content-Length: 13
< Server: Jetty(11.0.12)
<
* Connection #0 to host localhost left intact
["ex:Andrew"]

MacBook-Pro-6:~ ajohnson$ curl -v --location --request POST 'http://localhost:58090/fluree/query' --header 'Origin: http://localhost:3000' --header 'Content-Type: application/json' --data-raw '{
    "ledger": "examples/headers",
    "query": {
        "select": "?s",
        "where": [
            ["?s", "rdf:type", "ex:LakeMonster"]
        ]
    }
}'
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 127.0.0.1:58090...
* Connected to localhost (127.0.0.1) port 58090 (#0)
> POST /fluree/query HTTP/1.1
> Host: localhost:58090
> User-Agent: curl/7.84.0
> Accept: */*
> Origin: http://localhost:3000
> Content-Type: application/json
> Content-Length: 160
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 400 Bad Request
< Content-Type: application/json;charset=utf-8
< Content-Length: 101
< Server: Jetty(11.0.12)
<
* Connection #0 to host localhost left intact
{"error":"db/invalid-query","message":"Undefined RDF type specified: http://example.org/LakeMonster"}
```
