### ISSUE TITLE
Support "@context" in a query, in addition to "context"

### ISSUE THREAD

**Issue by bplatz** [fluree/http-api-gateway#28]
In transactions, the user must use either `"@context"` or `:context` if in CLJ, but for queries we only accept `"context"` or `:context`.

We should support the use of `"@context"` in queries for consistency, as we are using users utilize that assuming it is the correct syntax, however it isn't currently.

**Comment by dpetran** [comment]
Going to wait until the fix for https://github.com/fluree/db/issues/414 lands to complete this.
