### ISSUE TITLE
Failed to load API definition when accessing localhost:8090

### ISSUE THREAD

**Issue by haliechm** [fluree/http-api-gateway#34]
I believe a fix to this is adding a set of middleware in http.clj:

![oo02](https://user-images.githubusercontent.com/40928883/222467208-91595c02-a0ff-41d9-8b88-669df6d75efa.png)

**added:**
  muuntaja/format-negotiate-middleware 
                             muuntaja/format-response-middleware 
                             muuntaja/format-request-middleware

### **Issue**

When accessing localhost:8090:
![oo00](https://user-images.githubusercontent.com/40928883/222467410-f7fd9801-94de-43bd-9f61-f95cd8f378f7.png)
![oo01](https://user-images.githubusercontent.com/40928883/222467432-077fd527-f2d8-49a0-8c33-bb128dcf690e.png)

**Comment by cap10morgan** [comment]
That looks right, @haliechm. Thanks! Want to submit a PR? (If you're in the middle of other work I can do it, though.)

**Comment by haliechm** [comment]
ah you know what, it looks like I don't have access rights to push to this repo @cap10morgan

**Comment by cap10morgan** [comment]
> ah you know what, it looks like I don't have access rights to push to this repo @cap10morgan

In those cases you can issue a PR from a fork to your personal GitHub account, but in _this_ particular case I can just give you access :)

**Comment by haliechm** [comment]
@cap10morgan good to know thank you - I haven't done that before. And the access works, thanks

**Comment by cap10morgan** [comment]
Fixed by #35
