### ISSUE TITLE
Support for /commit (e.g. /block)

### ISSUE THREAD

**Issue by aaj3f** [fluree/http-api-gateway#7]
Work specific to http-api-gateway in support of sibling ticket: https://github.com/fluree/db/issues/333

**Comment by aaj3f** [comment]
@mpoffald I am assuming if the HTTP API is exposed on `http-api-gateway` and not `db` then this issue still needs to remain open, right? wrt the Needs Specification label, is there any actual additional information needed for this other than the description / acceptance criteria / impl. details that are documented on fluree/db#333?

**Comment by dpetran** [comment]
This requires no extra work as we've merged the commit query functionality into the history api endpoint.
